### ISSUE TITLE
Pertained models with 512 or 256 resolutions?

### ISSUE THREAD

**Issue by sailor002** [omertov/encoder4editing#10]
Hi, thanks for the excellent work. I see that you have a pretrained model for FFHQ 1024x1024 resolution. Do you have one for 512 or 256?

**Comment by yuval-alaluf** [comment]
Hi @sailor002 , we do not have FFHQ models for 512 or 256 resolutions. 
However, may I ask why you would like to use a smaller resolution generator? Our encoders are trained on inputs of size 256x256, but we generate images at 1024x1024 resolution. Therefore, you can use the smaller-sized inputs but get the benefits of a higher resolution generator with little cost.

**Comment by sailor002** [comment]
Thanks for the quick reply @yuval-alaluf. Actually, we are assessing the eligibility of "e4e" to be used in a production project where we plan to work with 512 resolution images. So anything above the necessary resolution will overuse resources and prolong execution times. By the way, my impression is that e4e outperforms idinvert (which we are currently experimenting with) in every aspect, even when a moderate post-optimization is applied to idinvert. So, I really appreciate your work.

So maybe we can retrain your model in lower resolutions. Do you think that we can benefit from your pretrained model by copying its available weights to the lower resolution model so that we don't start from scratch? Thanks...

**Comment by omertov** [comment]
Hi @sailor002!

The model consists of 2 networks - a pretrained StyleGAN generator (checkpoint taken from the official NVIDIA repository) and the e4e encoder.

If you have a lower resolution StyleGAN2 generator, I would advise to retrain the e4e encoder from scratch since the latent space of the 1024x1024 generator and your generator are not the same.

**Comment by sailor002** [comment]
By the way, the main reason I'm looking for a lower resolution is that the latent code produced by your model has a dimension of 18x512, which can be used by the official Stylegan2 ffhq-1024 pretrained model. However, what we need is a latent code that is compatible with the official ffhq-512 model, which should have 16x512 latent dimension. As far as I know, there is no way to use a latent with the different resolution Stylegan2 models.

**Comment by sailor002** [comment]
Thanks, @omertov. We'll probably go that way then.

**Comment by Harsha-Musunuri** [comment]
@sailor002 did you get a chance to train the 256x256 model ?

**Comment by li-car-fei** [comment]
@sailor002 did you get a chance to train the 256x256 model ?
