### ISSUE TITLE
Inconsistent device when loading pSp model

### ISSUE THREAD

**Issue by ktrapeznikov** [omertov/encoder4editing#11]
pSp model uses `device` stored in the `opts` field of the checkpoint when loading `latent_avg` 

https://github.com/omertov/encoder4editing/blob/03f17f3db53329da815102a2018750522cd63ed9/models/psp.py#L94

In the currently saved checkpoint that defaults to `cuda:0`. So when loading the model to another device this will cause an error since model and `latent_avg` will b on different devices.
 
Adding:

`opts['device'] = device`

**after** this line should do the trick

https://github.com/omertov/encoder4editing/blob/03f17f3db53329da815102a2018750522cd63ed9/utils/model_utils.py#L8

**Comment by omertov** [comment]
Hi @ktrapeznikov!
Thanks for pointing that out! I've incorporated your suggested change to the repo.
I plan on adding the latent average code as a buffer to the encoder, so the encoder will not depend on the pSp framework.
Until then it seems like this change indeed solves the problem.
