### ISSUE TITLE
How could you get directions for age, smile and pose?

### ISSUE THREAD

**Issue by koojagyum** [omertov/encoder4editing#12]
Hi. Thanks for your great work!

Is it possible to obtain other directions(about face)?
You said you used StyleFlow. But StyleFlow needs latent codes and facial attributes(MS-API).
And it uses W-latents space(18 x 512) other than Z-space.
How did you do that? Am I missing about StyleFlow?

**Comment by omertov** [comment]
Hi @koojagyum!
All 4 editing techniques displayed in the paper (InterFaceGAN, GANSpace, SeFa, and StyleFlow) can be used to edit face images after their inversion into a W(k,*) 18x512 latent code (Using the e4e encoder for example).

Other then InterFaceGAN, we did not train GANSpace, SeFa, or StyleFlow for additional editing directions, meaning we used the existing capabilities of each technique.

To train InterFaceGAN, you can use their <a href="https://github.com/genforce/interfacegan">official repository</a>, but you need to sample many w(,) [1x512 style vector] vectors and obtain matching labels for each of the images produced by the style vector (you can read more about it at their official repository).

**Comment by koojagyum** [comment]
Thanks for your clear answer and comment.
Actually, I tried gender editing using [stylegan2-distillation](https://github.com/EvgenyKashin/stylegan2-distillation), and it worked somehow.
And even StyleGAN-v1 boundaries from [InterFaceGAN](https://github.com/genforce/interfacegan) also worked.
