### ISSUE TITLE
how get other interfacegan_direction file?

### ISSUE THREAD

**Issue by TomatoBoy90** [omertov/encoder4editing#16]
your job very great!You provided three interfacegan_direction files:age.pt,pose.pt and smile.pt.
However,if I want to get other direction results,how get other interfacegan_direction file?
And I  compared interfacegan with your file, and the result seems to be different. Can't we use a file directly.

**Comment by omertov** [comment]
Hi @TomatoBoy90!
To obtain new editing directions, you should follow the <a href='https://github.com/genforce/interfacegan'>official InterFaceGAN repository's</a> guidelines, <a href='https://github.com/omertov/encoder4editing/issues/9'>in this this issue</a> we wrote how we obtained our 3 editing directions so feel free to check it out (note that you need to use an attribute classification network to label each style vector).

The boundary files from the InterFaceGAN repository were obtained for the pretrained StyleGAN1's latent space, while we trained the boundaries for the pretrained StyleGAN2 (hence the difference you are experiencing).

**Comment by TomatoBoy90** [comment]
thank you for your reply quickly.I read InterFaceGAN repository,but seem it need to train svm model，as a supervised learning, it  needs label，how to get the label?

**Comment by TomatoBoy90** [comment]
Training a SVM model, but how does the machine know which face attribute we need to train?

**Comment by omertov** [comment]
We used a pretrained network to label each StyleGAN image.
For example, after sampling a style vector w, we generated the corresponding image I=Generator(w) and used a pretrained age classification network to obtain the label age_I = AGE_NET(I) to train the SVM for the age direction.

**Comment by TomatoBoy90** [comment]
> We used a pretrained network to label each StyleGAN image.
> For example, after sampling a style vector w, we generated the corresponding image I=Generator(w) and used a pretrained age classification network to obtain the label age_I = AGE_NET(I) to train the SVM for the age direction.
thanks,how many samples should I take for style vector w? How many samples did you take it?

**Comment by yuval-alaluf** [comment]
Hi @TomatoBoy90 ,
We used the default procedure used in InterFaceGAN. If I remember correctly, this means we used 500,000 randomly sampled w vectors. We then took the 10,000 samples that got the highest attribute score to be the positive samples and 10,000 samples with the lowest scores to be our negative samples.

**Comment by TomatoBoy90** [comment]
thank you reply so detailed and generous.Wish you a happy life

**Comment by omertov** [comment]
Good luck with your experiments!
I am closing the issue :)
