### ISSUE TITLE
when input face angle is big , output img  look like the slim face

### ISSUE THREAD

**Issue by chinasilva** [omertov/encoder4editing#20]
Hi @omertov:
Many thanks for your excellent works. However, I have a questions about training my data. my output just like this：
![image](https://user-images.githubusercontent.com/16743182/115983321-0bd31f00-a5d3-11eb-9605-168de060b71c.png)
![image](https://user-images.githubusercontent.com/16743182/115983449-b51a1500-a5d3-11eb-92a2-fb3c0d679aed.png)

Best wishes.

**Comment by omertov** [comment]
Hi @chinasilva!
It seems like you are training the encoder for the frontalization task, am I correct?
Are the images provided as input aligned?

**Comment by chinasilva** [comment]
i find this error，when i change this file transforms_config.py，put transform_source to transforms.Compose，it will like that。thank u

**Comment by chinasilva** [comment]
i find this error，when i change this file transforms_config.py，put transform_source to transforms.Compose，it will like that。thank u

**Comment by zeta7337** [comment]
> 

i meet the same problem.how do you fix it?can explain in detail?thank you

**Comment by ZziTaiLeo** [comment]
> 

sorry, I get the same problem, but I just use default transfors_config.py. How do you fix it? May I look you corrected pictures?
