### ISSUE TITLE
# GANSpace

### ISSUE THREAD

**Issue by GewGaw74** [omertov/encoder4editing#21]
Hi, what other parameters besides the ones below can i change, where can i find the complete list?
['eye_openness', 'smile', 'trimmed_beard', 'white_hair', 'lipstick']
how to properly manipulate these code values?
![image](https://user-images.githubusercontent.com/81899474/115990018-85224000-a5da-11eb-9493-598a66d1576c.png)

**Comment by omertov** [comment]
Hi @GewGaw74!
The direction were taken from the official GANSpace repository <a href="https://github.com/harskish/ganspace/blob/master/notebooks/figure_teaser.ipynb">here</a>.
As we have not used GANSpace over the faces domain in the paper, I kept only several editings that i found to work best on the specific test image, but there are more available for you to try on your inversions. 
(Note that those directions were manually selected by the GANSpace authors based on experiments on sampled w style codes)
