### ISSUE TITLE
when training on my dataset,person eye getting smaller and smaller，but similarity getting more close 1

### ISSUE THREAD

**Issue by chinasilva** [omertov/encoder4editing#23]
Hi @omertov :
Many thanks for your excellent works. However, I have a questions about training my data. my output just like this：
![image](https://user-images.githubusercontent.com/16743182/116398288-34207f00-a85a-11eb-9a9e-4fe782106310.png)

after few iterations，it will be like this： eye getting smaller and smaller，similarity getting more close 1
![image](https://user-images.githubusercontent.com/16743182/116398384-52867a80-a85a-11eb-8694-127d8ebda139.png)

I don't know why
Best wishes.

**Comment by omertov** [comment]
Hi @chinasilva!
Can you share your objective function which causes this behaviour?

As for the similarity improvement, we are basing our Identity loss on the pretrained arcface model, and these side effects might come from there.
Another guess might be the alignment of the training images. 
As the alignment is performed based on the eyes location, in case the input images are not aligned it is possible that the encoder learns to maximize the objective function when the eyes are aligned (which causes smaller discriminative loss, as all w codes result in an aligned image) and closed (perhaps the open eyes with the adjusted alignment is recognized as a different person by the face recognition network).

This is just a guess, I would suggest making sure that the training images are aligned, perhaps sharing your objective function will shed some more light on the problem.

**Comment by chinasilva** [comment]
thank u very patient explain. 
1.I find only inference use aligned images at your code, you mean training images must be aligned ？i find this image different from after aligned image.
2.my objective function just like your 'coach.py'
3.'opt.json' like this file
[opt.log](https://github.com/omertov/encoder4editing/files/6444990/opt.log)

**Comment by omertov** [comment]
Hi @chinasilva ,
Ineed, the training images should be aligned.
As we are training the encoder to produce latent codes within the W space, it will not provide the desired results unless the images are aligned the same way the images from the W space are aligned.

**Comment by chinasilva** [comment]
I jsut do it as you said,I get the right result,Thank you for your excellent works. Thanks again!
