### ISSUE TITLE
Pretrained discriminator model

### ISSUE THREAD

**Issue by seokg** [omertov/encoder4editing#24]
Thank you for the nice work.

I was wondering if you guys have and can share the pretrained discriminator pt file.

Thank you.

**Comment by omertov** [comment]
Hi @seokg!
I believe I still got it saved somewhere, which domain are you interested in?

**Comment by seokg** [comment]
I am looking for the weights of FFHQ discriminator.
Thanks for the fast reply.

**Comment by omertov** [comment]
Closing the issue :)
