### ISSUE TITLE
how to use the styleGAN model trained on tensorflow ?

### ISSUE THREAD

**Issue by C-hongfei** [omertov/encoder4editing#25]
How did you get your styleGAN pre training model? I want to use the styleGAN model trained on tensorflow to train e4e. What should I do?

**Comment by omertov** [comment]
Hi @C-hongfei,
<a href="https://github.com/omertov/encoder4editing/issues/4">here</a> is a related issue.
You will need to convert your trained model into a checkpoint compatible with rosinality's <a href="https://github.com/rosinality/stylegan2-pytorch">stylegan2-pytorch repository</a>.
In his repository there is a conversion script suitable for NVIDIA's TensorFlow repositories.

**Comment by C-hongfei** [comment]
Thank you. I think that would be a great help!

**Comment by omertov** [comment]
Good luck with your experiments!
I am closing the issue :)
