### ISSUE TITLE
How to train on other animal dataset

### ISSUE THREAD

**Issue by UniBester** [omertov/encoder4editing#26]
If I want to train this model on other dataset like animal faces, but I don't have the correspond pretrained stylegan model. How can I train the stylegan model by myself?

**Comment by omertov** [comment]
Hi @UniBester!

As this repository is intended for training an encoder for a pre-trained StyleGAN2 model, I would suggest using either rosinality's stylegan2-pytorch repository or one of the official NVIDIA repositories to train the StyleGAN based on your images.

After you obtain a trained model you can use the repository to train the encoder :)

**Comment by UniBester** [comment]
I‘ve got it. Thanks a lot

**Comment by omertov** [comment]
Closing the issue, feel free to open a new issue in case someting else is needed :)
