### ISSUE TITLE
How to train for paired data?

### ISSUE THREAD

**Issue by cvmlddev** [omertov/encoder4editing#3]
Hi, Sorry if it's a silly issue.
I am a bit confused, Is it just the encoder? 

How can we use it to train it on paired dataset , For example male to female, human to toon, etc?

**Comment by omertov** [comment]
Hi @cvmlddev,
Indeed, this repository contains the implementation details of our e4e StyleGAN encoder. 
As mentioned in the paper, here we introduce means to control the discussed tradeoffs using designated loss terms.

If it suits your needs, you can use the proposed encoder and training scheme in an image-to-image translation framework (see pSp for example).
