### ISSUE TITLE
I had trained a styleGAN in my dataset, but in this ckpt, we miss the key named 'latent_avg', how to get it?

### ISSUE THREAD

**Issue by ssxxx1a** [omertov/encoder4editing#30]
thanks.

**Comment by omertov** [comment]
Hi @ssxxx1a.
The average latent is obtained from sampling many (usually thousands) of latent codes and averaging them to get the average code.
Usually the repositories provide a build in function for obtaining this average code, for example see <a href="https://github.com/rosinality/stylegan2-pytorch/blob/master/model.py#L488">this function</a> in rosinality's repository.

After obtaining the average code, you should save it as a part of the checkpoint under the 'latent_avg' key.

Best,
Omer

**Comment by yuval-alaluf** [comment]
To add to @omertov's answer, when you initialize the network in the following lines:
https://github.com/omertov/encoder4editing/blob/73c60bdbad4821e02ee55a5ef107bbdbe6f9963c/training/coach.py#L37-L38
you can add the following snippet: 
```python
if self.net.latent_avg is None:			
    self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0].detach()
```
This will estimate the average latent and store it as part of the network. Then training can continue as is normal.

**Comment by ssxxx1a** [comment]
> To add to @omertov's answer, when you initialize the network in the following lines:
> https://github.com/omertov/encoder4editing/blob/73c60bdbad4821e02ee55a5ef107bbdbe6f9963c/training/coach.py#L37-L38
> 
> 
> you can add the following snippet:
> ```python
> if self.net.latent_avg is None:			
>     self.net.latent_avg = self.net.decoder.mean_latent(int(1e5))[0].detach()
> ```
> 
> This will estimate the average latent and store it as part of the network. Then training can continue as is normal.

**Comment by ssxxx1a** [comment]
ohhh! 
thanks both for your reply !
