### ISSUE TITLE
train on owned dataset

### ISSUE THREAD

**Issue by mmiaz** [omertov/encoder4editing#31]
Hi, thanks for the amazing work. I am still confused for the training dataset, do I not need to put any class label to the images? Looking forward to your reply. Thanks

**Comment by omertov** [comment]
Hi @mmiaz!
For the inversion task, there is no need for any class labels, as the input image ("x") given to the encoder, is also the target ("y") of the inversion process.

Best,
Omer

**Comment by mmiaz** [comment]
> Hi @mmiaz!
> For the inversion task, there is no need for any class labels, as the input image ("x") given to the encoder, is also the target ("y") of the inversion process.
> 
> Best,
> Omer

Thanks for the reply!
