### ISSUE TITLE
Does progressive training delta_ws have a big influence on the result?

### ISSUE THREAD

**Issue by insomnia250** [omertov/encoder4editing#32]
Thanks for sharing your work!

I'm a little curious about whether "progressive training delta_ws" have a big influence on the result. Can I just train those delta_ws together/simultaneously? Have you tried this direct training strategy?

**Comment by omertov** [comment]
Hi @insomnia250!
We did run such ablation, and the main findings showed a faster convergence (less training iterations), as well as slightly better reconstructions. 

Best,
Omer
