### ISSUE TITLE
About  LatentCodesPool in the code

### ISSUE THREAD

**Issue by diaodeyi** [omertov/encoder4editing#34]
Hi, i want to know the purpose for the design of the LatentCodesPool. The reason for designing 50% to use the previous W code?

**Comment by omertov** [comment]
Hi @diaodeyi,
Yes you are correct, this has been done in other GAN papers (e.g. CycleGAN) to include some memorization for the discriminator, and we thought it would be interesting to add it here as well.

Best,
Omer
