### ISSUE TITLE
About some details of the  PsP_encoder.py

### ISSUE THREAD

**Issue by diaodeyi** [omertov/encoder4editing#36]
Hi , Thanks for your great work ,I want to konw why you set" i == coarse_ind' not ">=",in this way, only one style vector will follow FPN's middle features. And the follow is the same way.
            if i == self.coarse_ind:
                p2 = _upsample_add(c3, self.latlayer1(c2))  # FPN's middle features
                features = p2
            elif i == self.middle_ind:
                p1 = _upsample_add(p2, self.latlayer2(c1))  # FPN's fine features
                features = p1

**Comment by omertov** [comment]
Hi @diaodeyi!
The intent is to calculate p2 and p1 only once (at the first iteration they are needed), and then store them at the `features` varialbe, which will be used by the following iterations (until replaced).

i.e. 
for 0 <= i < coarse_ind, `features = c3`  (use first pyramid level for the coarse layers codes)
for coars_ind <= i < middle_ind, `features = p2`  (use the second pyramid level for the middle layers codes)
for middle_ind <= i  `features = p1`  (use the third pyramid level for the fine layers codes)

Best,
Omer
