### ISSUE TITLE
About the number of iterations

### ISSUE THREAD

**Issue by mdd876** [omertov/encoder4editing#39]
Hi, thank you for the nice work.

I was wondering how many iterations you trained for the provided "FFHQ Inversion Pretrained Model".

Thank you.

**Comment by omertov** [comment]
Hi @mdd876!
The checkpoint for the FFHQ domain was obtained after 250k iterations.

Best,
Omer

**Comment by xudonmao** [comment]
Hi, Omer,

Thanks for your kind reply!
