### ISSUE TITLE
StyleGAN2-ada-pytorch models supported?

### ISSUE THREAD

**Issue by TheodoreGalanos** [omertov/encoder4editing#4]
Hello and thanks for sharing your code!

I am trying to train an encoder on a stylegan2-ada-pytorch model that I have pretrained. I am using a .pkl file (as is the default output of that repo) and I am getting errors (related to the ada repo in fact). Is it possible to use that model here, or do I need to convert it somehow?

Thanks in advance!

**Comment by omertov** [comment]
Hi @TheodoreGalanos!
This repository uses the stylegan2 implementation by rosinality: <a>https://github.com/rosinality/stylegan2-pytorch</a>.
To load your trained model you will need to first convert it into a checkpoint compatible with the above repository.

(From a quick glance I saw a <a href="https://github.com/NVlabs/stylegan2-ada-pytorch/issues/44">relevant issue</a> in stylegan2-ada-pytorch, after which the convert_weight.py script from the rosinality repository can be used)

**Comment by TheodoreGalanos** [comment]
Thanks just saw that too, would be great. Really want to use your implementation!

**Comment by omertov** [comment]
For future reference, it seems like there is a way for converting the stylegan2-ada-pytorch model: https://github.com/rosinality/stylegan2-pytorch/issues/206.

Feel free to reopen the issue in case the suggested solution does not work :)
