### ISSUE TITLE
How to sample latent codes from the W space?

### ISSUE THREAD

**Issue by falloncandra** [omertov/encoder4editing#40]
Hi, as mentioned in [here](https://github.com/omertov/encoder4editing/issues/9) and [here](https://github.com/omertov/encoder4editing/issues/16), we need to randomly sample w vectors in order to learn the interfacegan_direction.

However, I have no idea how to randomly sample the w vectors. Would you kindly tell me how to do it (using some function in this repo probably?) 

Thank you very much!

**Comment by omertov** [comment]
Hi @falloncandra!
You can check out the first 2 lines in the `sample_real_and_fake_latents` function, which sample a Z vector and pass it into the mapping network to obtain a W space latent code (denoted there as `real_w`): https://github.com/omertov/encoder4editing/blob/2795aa93714e03ce4d8b70d4d803e4718f5c63d4/training/coach.py#L426

Best,
Omer

**Comment by falloncandra** [comment]
Hi, thank you very much for your help! :)

**Comment by omertov** [comment]
Glad it helped! closing the issue :)
