### ISSUE TITLE
interface gan pt

### ISSUE THREAD

**Issue by Gutianpei** [omertov/encoder4editing#46]
Hello,

Thanks for the amazing work! I'm running your code and I wondered where does age.pt, smile.pt and pose.pt come from. I checked interface gan repo and they did not provide it. Could you help me with this issue? Thank you very much!

**Comment by omertov** [comment]
Hi @Gutianpei!
We obtained the editing directions by running the InterFaceGAN method: 
1. Sample random style codes.
2. Generate the corresponding images.
3. Label each image using a pretrained network (for example - age classification network)
4. Run the InterFaceGAN repo using the (code, label) pairs obtained above.

See <a href="https://github.com/omertov/encoder4editing/issues/16">this issue</a> for more details.

Best,
Omer
