### ISSUE TITLE
Questions about Table 7 in the paper

### ISSUE THREAD

**Issue by wty-ustc** [omertov/encoder4editing#48]
What losses are used for pSp training for the car inversion in Table 7, and are there moco loss used?
Thank you!

**Comment by omertov** [comment]
Hi @wty-ustc!
We used the L2 + LPIPS losses for the pSp comparison.
As the MOCO based loss was introduced in our paper (and not in pSp), we have not used it in the comparison.
However, config A in table 6 is equivalent to pSp with the MOCO loss (for the cars domain).

Best,
Omer
