### ISSUE TITLE
No such file or directory: 'pretrained_models/model_ir_se50.pth'

### ISSUE THREAD

**Issue by azyp19970815** [omertov/encoder4editing#5]
When I run train.py, it will prompt:  No such file or directory: 'pretrained_models/model_ir_se50.pth'，
Where can I find the ‘’model_ir_se50.pth‘’?
If you have time, can you help me solve this problem, thank you very much！
![image](https://user-images.githubusercontent.com/67415970/109938302-d153b100-7d0a-11eb-9c66-49010db4379f.png)

**Comment by yuval-alaluf** [comment]
Hi @azyp19970815 , you can find the model file in the README: 
https://github.com/omertov/encoder4editing#pretrained-models

**Comment by azyp19970815** [comment]
> 嗨@ azyp19970815，您可以在自述文件中找到模型文件：[https](https://github.com/omertov/encoder4editing#pretrained-models) :
> [//github.com/omertov/encoder4editing#pretrained-models](https://github.com/omertov/encoder4editing#pretrained-models)

Thank you very much, but I encountered a new problem. When I set ‘’train_source_root‘’, it shows is not a valid directory.
![屏幕截图 2021-03-04 192909](https://user-images.githubusercontent.com/67415970/109958013-b3914680-7d20-11eb-9d2d-219cb8166558.png)

**Comment by yuval-alaluf** [comment]
Notice that your error occurs in line 227 when you try to define the test data. However, your test data (`celeba_test`) is empty and therefore you are obtaining the error. You should fill in this value with a valid path.

**Comment by omertov** [comment]
Hi @azyp19970815,
As for your problem, @yuval-alaluf is correct.

Also, from looking at your project directory, it seems that the encoder4editing-main/ffhq directory contains the pretrained ffhq encoder.
Notice that the `dataset paths` in the `paths_config.py` should point to the dataset directory containing the training images.
