### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by Gemma77** [omertov/encoder4editing#50]
Hi, I notice the Pretrained IR-SE50 model which is used for ID loss during training is trained based on face dataset. If I wanna train the model for car dataset whose ID feature shows big difference from FaceID's. Is it also work fine for the ID loss? Or is it better to replace the pretrained model with the one trained based on car datset. Thank you!

**Comment by omertov** [comment]
Closing for now, feel free to open if more clarifications are needed!
