### ISSUE TITLE
Output is a Solid Color, Regardless of input

### ISSUE THREAD

**Issue by axumkevar** [omertov/encoder4editing#52]
I'm sure someone's had this issue before and I'm hoping it's an easy answer. I've got a jupyter notebook version forked from this that I've resolved all the dependencies as far as I can tell, but e4e is outputting a single brown box no matter what I do, either from the notebook or inference.py, no errors are output, it just only outputs brown boxes. I've tried increasing the image size in utils/common.py, only producing noise. I have since re-pulled the code, but still receiving brown boxes as output.

![example](https://user-images.githubusercontent.com/90418301/132967645-d2b193c5-eee9-4fd4-8f7f-5d16c4ff6492.png)

**Comment by omertov** [comment]
Hi @axumkevar,
When I run the notebook no such thing is happening, are you using the pretrained checkpoints provided in this repo?
perhaps there is a version mismatch between the installed packages and the ones in our e4e_env.yaml?

Best,
Omer

**Comment by axumkevar** [comment]
Strangely enough Styleclip itself produced the correct output from the latents, however I ran into a bigger issue with memory. Closing this issue as I believe the memory constraints are likely a culprit here.
