### ISSUE TITLE
Inference Playground errors out when trying to load pretrained model

### ISSUE THREAD

**Issue by aferriss** [omertov/encoder4editing#54]
Like the title says, calling `ckpt = torch.load(model_path, map_location='cpu')` in the colab causes an unpickling error.

It seems like maybe the .pt file isn't being downloaded correctly.

UnpicklingError                           Traceback (most recent call last)
<ipython-input-5-698ee78d7482> in <module>()
      1 model_path = EXPERIMENT_ARGS['model_path']
----> 2 ckpt = torch.load(model_path, map_location='cpu')
      3 opts = ckpt['opts']
      4 # pprint.pprint(opts)  # Display full options used
      5 # update the training options

1 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.

**Comment by omertov** [comment]
Hi @aferriss,
Does the issue still persist? 
i have not experienced this problem while running the Colab, which model did you try to load?

Best,
Omer
