### ISSUE TITLE
How to embed this into StyleGAN-ada?

### ISSUE THREAD

**Issue by JJack27** [omertov/encoder4editing#59]
Hi, thank you for your sharing. May I know how can I embed this encoder into a stylegan-ada?

**Comment by omertov** [comment]
Hi @JJack27!
Can you elaborate on what you are interested in?
Ill try to give a general answer: 
1. If you have a pretrained model from the StyleGAN-ADA repositories of NVIDIA, you can check out rosinality's stylegan2-pytorch repository for a conversion script which will create a checkpoint suitable for use in this repo.
2. If you wish to integrate any of NVIDIAs repositories, you should add the files defining the stylegan generator, and replace all the calls to rosinality's stlyegan2 generator in this repo with the appropriate API of the NVIDIA repo.

Best,
Omer

**Comment by JJack27** [comment]
Hi @omertov !

Thank you for you fast reply. I'm trying for the option 2. May I know where did you call the styleGAN2 the most? So that I can investigate and analyze if it's possible to replace it with stylegan-ada.

Regards,
Jack
