### ISSUE TITLE
How to train on my own data?

### ISSUE THREAD

**Issue by tearscoco** [omertov/encoder4editing#6]
Hi guys,

Really impressive work here!

I am wondering whether I can train on my own data and obtain a well-designed encoder for my in-domain issue instead of standard datasets of cats, horses, etc. Could you please give some instructions?

**Comment by yuval-alaluf** [comment]
Hi @tearscoco , 
The code design for e4e is very similar to that of [pixel2style2pixel](https://github.com/eladrich/pixel2style2pixel). Therefore, to train the e4e encoder on your own data, you can refer to the [instructions provided in the pSp repo](https://github.com/eladrich/pixel2style2pixel#preparing-your-data). Please let us know if you need more clarifications. 

@omertov , do you think it would be helpful to add a similar `Preparing your Data` section to this repo?

**Comment by omertov** [comment]
Hi @tearscoco!
As @yuval-alaluf mentioned, this repository builds upon the pSp repository's project structure and training management.

I have added a section to the README explaining the required steps to train the encoder on your own dataset, see <a href="https://github.com/omertov/encoder4editing/blob/main/README.md#training-on-your-own-dataset">here</a>.

**Comment by tearscoco** [comment]
Thanks, guys! It really helps a lot!

**Comment by tearscoco** [comment]
@yuval-alaluf one more question! I found that the code is run with a single GPU and there was no setting for distribution options. Is it possible to use multiple GPUs and accelarate the training process?

**Comment by yuval-alaluf** [comment]
> @yuval-alaluf one more question! I found that the code is run with a single GPU and there was no setting for distribution options. Is it possible to use multiple GPUs and accelarate the training process?

Please see the following issue in the pixel2style2pixel repo: https://github.com/eladrich/pixel2style2pixel/issues/27

**Comment by tearscoco** [comment]
Thank you @yuval-alaluf  and @omertov for your quick responses, I've obtained the desired results from my own training data.
![image](https://user-images.githubusercontent.com/24731456/111722097-21e71480-889c-11eb-8b1e-9894f4fc6161.png)

If I wanna get consistent edit of my images, should I get the latent code first and let it go through the editing direction checkpoint (ex. obtained from styleGAN2 factorization)?

**Comment by yuval-alaluf** [comment]
> If I wanna get consistent edit of my images, should I get the latent code first and let it go through the editing direction checkpoint (ex. obtained from styleGAN2 factorization)?

Exactly. You can run inference using the provided script to extract the image latents. Then, you can use the provided editing scripts to learn edit directions (e.g., using SeFa)

**Comment by mmiaz** [comment]
@tearscoco Hi, i am working on similar apparel dataset, did you train your own styleGAN first and use e4e to do the latent code encoder training? Thanks!

**Comment by zxy2020** [comment]
> Thank you @yuval-alaluf and @omertov for your quick responses, I've obtained the desired results from my own training data. ![image](https://user-images.githubusercontent.com/24731456/111722097-21e71480-889c-11eb-8b1e-9894f4fc6161.png)
> 
> If I wanna get consistent edit of my images, should I get the latent code first and let it go through the editing direction checkpoint (ex. obtained from styleGAN2 factorization)?

Excuse me,  what is the number of pictures in your custom dataset to get such a result？
