### ISSUE TITLE
Support StyleGAN3

### ISSUE THREAD

**Issue by tommy19970714** [omertov/encoder4editing#61]
StyleGAN3 is now available.
https://github.com/NVlabs/stylegan3

Do you have plan to support StyleGAN3?

**Comment by ZziTaiLeo** [comment]
This is very useful for editing features to produce animation effects，I can't wait to see this project support stylegan3.

**Comment by yuval-alaluf** [comment]
We've actually already begun experimenting with various encoders for StyleGAN3, but training a proper encoder is a bit tricky. Feel free to take a look at my more detailed answer here: https://github.com/yuval-alaluf/restyle-encoder/issues/45#issuecomment-943503066

Interestingly, some initial experiments showed that current latent space editing techniques result in edits that are much more entangled than what you would get with SG2. Therefore, it seems like using SG3 for editing real images may lead to some undesirable results (using currently available techniques)

**Comment by dayu1979** [comment]
i trained one 
https://github.com/dayu1979/stylegan3encoder

**Comment by omertov** [comment]
Stumbled upon this old issue, thought to share the great work of Alaluf and Patashnik et al. <a href=https://github.com/yuval-alaluf/stylegan3-editing>Third Time's the Charm? Image and Video Editing with StyleGAN3</a> which enable StyleGAN3 training of e4e (ReStyle-e4e with 1 iteration).
