### ISSUE TITLE
Other directions from InterfaceGAN trained on StyleGAN2 

### ISSUE THREAD

**Issue by V-Sher** [omertov/encoder4editing#7]
Thank you for an awesome repo!

Since InterfaceGAN is originally trained on the StyleGAN1 generator, it seems you retrained it using StyleGAN2 (for ease of comparison with your method). Did you generate directions other than age and smile, (for example pose)? If so, could you pls provide it as part of the repo?

Thanks

**Comment by omertov** [comment]
Hi @V-Sher!
The pose editing presented in the figures were obtained using StyleFlow, I did not train InterfaceGAN for the StyleGAN2 pose direction.

With that said, I do plan on adding more editing options to the repo in the future, and I'll be sure to add further editing directions once obtained.
