### ISSUE TITLE
How to add the eye glasses just like the paper shows?

### ISSUE THREAD

**Issue by HKCityUmian** [omertov/encoder4editing#75]
HI, I wonder how to add the eye glasses to the real face, just like the figures of paper show？THANKS!

**Comment by omertov** [comment]
Hi @HKCityUmian,
Sorry for the long response time!
For documentation sake and in case this is still relevant, the glasses editing were obtained using <a href=https://github.com/RameenAbdal/StyleFlow>StyleFlow</a> editing of our inferred latent code.
