### ISSUE TITLE
 Training does not proceed.

### ISSUE THREAD

**Issue by leeisack** [omertov/encoder4editing#76]
The generator trained the e4e encoder with the pt file trained with rosinality's stylegan2-pytorch, but it stops like this.

python scripts/train.py --dataset_type my_data_encode --exp_dir ./new_gen_test/ --start_from_latent_avg --use_w_pool --w_discriminator_lambda 0.1 --progressive_start 20000 --id_lambda 0.5 --val_interval 10000 --max_steps 250000 --stylegan_size 1024 --stylegan_weights ./000000.pt --workers 8 --batch_size 8 --test_workers 4
{'batch_size': 8,
 'board_interval': 50,
 'checkpoint_path': None,
 'd_reg_every': 16,
 'dataset_type': 'my_data_encode',
 'delta_norm': 2,
 'delta_norm_lambda': 0.0002,
 'encoder_type': 'Encoder4Editing',
 'exp_dir': './new_gen_test/',
 'id_lambda': 0.5,
 'image_interval': 100,
 'keep_optimizer': False,
 'l2_lambda': 1.0,
 'learning_rate': 0.0001,
 'lpips_lambda': 0.8,
 'lpips_type': 'alex',
 'max_steps': 250000,
 'optim_name': 'ranger',
 'progressive_start': 20000,
 'progressive_step_every': 2000,
 'progressive_steps': [0,
                       20000,
                       22000,
                       24000,
                       26000,
                       28000,
                       30000,
                       32000,
                       34000,
                       36000,
                       38000,
                       40000,
                       42000,
                       44000,
                       46000,
                       48000,
                       50000,
                       52000],
 'r1': 10,
 'resume_training_from_ckpt': None,
 'save_interval': None,
 'save_training_data': False,
 'start_from_latent_avg': True,
 'stylegan_size': 1024,
 'stylegan_weights': './000000.pt',
 'sub_exp_dir': None,
 'test_batch_size': 2,
 'test_workers': 4,
 'train_decoder': False,
 'update_param_list': None,
 'use_w_pool': True,
 'val_interval': 10000,
 'w_discriminator_lambda': 0.1,
 'w_discriminator_lr': 2e-05,
 'w_pool_size': 50,
 'workers': 8}
Loading encoders weights from irse50!
Loading decoder weights from pretrained!
Loading MOCO model from path: pretrained_models/moco_v2_800ep_pretrain.pth
Loading dataset for my_data_encode
Number of training samples: 35993
Number of test samples: 9000
Changed progressive stage to:  ProgressiveStage.WTraining
Traceback (most recent call last):
  File "scripts/train.py", line 88, in <module>
    main()
  File "scripts/train.py", line 29, in main
    coach.train()
  File "./training/coach.py", line 113, in train
    loss_dict = self.train_discriminator(batch)
  File "./training/coach.py", line 384, in train_discriminator
    real_w, fake_w = self.sample_real_and_fake_latents(x)
  File "./training/coach.py", line 430, in sample_real_and_fake_latents
    fake_w = fake_w + self.net.latent_avg.repeat(fake_w.shape[0], 1, 1)
AttributeError: 'NoneType' object has no attribute 'repeat'

Does it work well with pt files trained with rosinality's stylegan2-pytorch ?

**Comment by zhuzhu18** [comment]
Maybe there is no "latent_avg" in your stylegan2 weights

**Comment by zzzandxxx** [comment]
me too

**Comment by omertov** [comment]
Hi @leeisack,
Sorry for the long response time,
Indeed it seems like the checkpoint did not have the latent_avg code stored, I have commited a fix where it is computed when the encoder uses the `start_from_latent_avg` flag.

Thanks @zhuzhu18 for helping out!

Best,
Omer
