### ISSUE TITLE
Pretrained model which can be loaded with 'load_from_train_checkpoint' method

### ISSUE THREAD

**Issue by SleyAI** [omertov/encoder4editing#78]
Hello, I would like to load your pretrained model by using the "load_from_train_checkpoint" in train.py in order to continue the training. The idea is to do transfer learning by learning a few steps on new images. It looks like that the pretrained model you provided (e4e_ffhq_encode.pt) is not suitable because it's missing some information like 'discriminator_state_dict' and more. I believe it is only for inference. Do you have a model which is suitable for further training? Thank you very much!

**Comment by wileewang** [comment]
Sorry to bother, do you find checkpoint of ffhq latent discriminator?
