### ISSUE TITLE
Some questions about Face Align in the code

### ISSUE THREAD

**Issue by Zenobia7** [omertov/encoder4editing#79]
Is there a reference for face align used in the code? Is it convenient to provide it? Can this algorithm be used to align bust images? Looking forward to your reply

**Comment by omertov** [comment]
Hi @Zenobia7,
Sorry for the long response time.
The alignment code can be found <a href="https://github.com/omertov/encoder4editing/blob/main/utils/alignment.py">here</a>.

We basically follow the FFHQ alignment process used to train the faces StyleGAN so we can run the inversion and compute the losses.

Perhaps looking up the FFHQ alignment process would give you the answer you are looking for?

Best,
Omer
