### ISSUE TITLE
Training e4e for 512*256 stylegan

### ISSUE THREAD

**Issue by jsaisagar** [omertov/encoder4editing#86]
Hi,

Is it possible to train e4e for resolutions 1024*512 or 512*256? If so, What changes do I need to make?

Thanks for any help

**Comment by tengolagan** [comment]
hi, i am interested in doing it as well. have you find your way to it ?

**Comment by jsaisagar** [comment]
Hi,

You will have to change the layer parameters in psp.py and encoders/psp_encoder.py
